language: node_js
node_js:
  - '12'
env:
  - CODECOV_TOKEN="eb1cd945-36f2-4e7b-a88a-bf5507867940"
cache:
  directories:
    - node_modules
script:
  - npm intall -g codecov
  - npm test && codecov
  - npm run build
